<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.jenkins-ci.plugins</groupId>
        <artifactId>plugin</artifactId>
        <version>4.88</version>
        <relativePath />
    </parent>

    <groupId>com.inflectra.spiratest.plugins</groupId>
    <artifactId>inflectra-spira-integration</artifactId>
    <version>4.0.2-SNAPSHOT</version>

    <packaging>hpi</packaging>
    <properties>
        <jenkins.version>2.462.3</jenkins.version>
        <additionalparam>-Xdoclint:none</additionalparam>
        <enforcer.skip>true</enforcer.skip>
        <testFailureIgnore>true</testFailureIgnore>
    </properties>

    <name>Spira Importer Plugin</name>
    <description>Plugin for Jenkins that allows Builds to be reported back into SpiraTest, SpiraPlan or SpiraTeam
    </description>
    <organization>
        <name>Inflectra Corporation</name>
        <url>https://www.inflectra.com</url>
    </organization>
    <inceptionYear>2012</inceptionYear>
    <url>https://github.com/jenkinsci/inflectra-spira-integration-plugin</url>
    <scm>
        <connection>scm:git:https://github.com/jenkinsci/inflectra-spira-integration-plugin.git</connection>
        <developerConnection>scm:git:git@github.com:jenkinsci/inflectra-spira-integration-plugin.git
        </developerConnection>
        <url>https://github.com/jenkinsci/inflectra-spira-integration-plugin</url>
        <tag>HEAD</tag>
    </scm>

    <repositories>
        <repository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>repo.jenkins-ci.org</id>
            <url>https://repo.jenkins-ci.org/public/</url>
        </pluginRepository>
    </pluginRepositories>
    <dependencies>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.11.0</version>
        </dependency>
    </dependencies>
</project>
